@baseUrl = http://localhost:3333
# 
# # @name create_account
# POST {{baseUrl}}/accounts
# Content-Type: application/json

# {
#   "name": "Gregory Praxedes",
#   "email": "gregoryrag@gmail.com",
#   "password": "123456"
# }

###

# # @name authenticate
# POST {{baseUrl}}/sync-services
# Content-Type: application/json

# {
#   "email": "gregoryrag@gmail.com",
#   "password": "123456"
# }

###

# @name create_appointment
POST {{baseUrl}}/appointments
Content-Type: application/json

{
  "date": "2025-04-26T12:00:00",
  "servicesIds": ["prod_NzleLbOmmqnw3E", "prod_NzlfW9d7KB18SY"],
  "clientId": "clientId"
}

###

# @name fecth-day-availability
GET {{baseUrl}}/day-availability?day=26&month=4&year=2025
Content-Type: application/json


###


# @name fecth-week-availability
GET {{baseUrl}}/week-availability
Content-Type: application/json


###



# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "gregoryteste@rocketseat.com.br"
}

###

