@baseUrl = http://localhost:3333

@authToken = {{authenticate.response.body.access_token}}

###
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "email": "gregoryrag@gmail.com",
  "name": "gregory",
  "password": "1234"
}

###


# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "gregoryrag@gmail.com",
  "password":"12345"
}



###
# @name create_appointment
POST {{baseUrl}}/appointments
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "date": "2025-04-26T12:00:00",
  "servicesIds": ["prod_NzlxrdfMouvqPq"]
}

###
# @name  FetchClient
GET {{baseUrl}}/client
Content-Type: application/json


###

###
# @name  EditClient
PUT {{baseUrl}}/client/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "gregory3"
}


###


# @name fecth-week-availability
GET {{baseUrl}}/day-availability?day=15&month=3&year=2024
Content-Type: application/json


###

# @name  fetch-appointment-by-client
GET {{baseUrl}}/fetch-appointments
Content-Type: application/json
Authorization: Bearer {{authToken}}

###









